export const messages = {
  USER_EXISTS: "User already exists",
  USER_CREATED: "User created successfully",
  USER_NOT_FOUND: "User not found",
  INVALID_CREDENTIALS: "Invalid credentials",
  LOGIN_SUCCESSFUL: "Login successful",
  ERROR_OCCURRED: "Something went wrong",
  TODO_CREATED: "Todo created successfully",
  TODOS_FETCHED: "Todos fetched successfully",
  TODO_UPDATED: "Todo updated successfully",
  TODO_DELETED: "Todo deleted successfully",
  TODO_NOT_FOUND: "Todo not found",
  TODO_STATUS_UPDATED: "Todo status updated successfully",
  TODO_FETCHED: "Todo fetched successfully",
  TODOS_FOUND: "Todos found successfully",
  USER_ID_REQUIRED: "User ID is required",
  QUERY_REQUIRED: "Query parameter is required",
  TAG_REQUIRED: "Tag is required",
  TAG_ADDED: "Tag added successfully",
  TAG_ALREADY_EXISTS: "Tag already exists for this user",
  TAGS_NOT_FOUND: "No tags found for this user",
  TAGS_FETCHED: "Tags fetched successfully",
  STUDENT_ADDED: "Student added successfully",
  STUDENT_NOT_FOUND: "Student not found",
  STUDENT_FETCHED: "Student fetched successfully",
  STUDENT_ALREADY_EXISTS: "Student already exists",
  BATCH_ADDED: "Batch added successfully",
  BATCH_NOT_FOUND: "Batch not found",
  BATCH_FETCHED: "Batch fetched successfully",
};